botpress/messaging

scripts/package.js

This PR fixes an issue where SQLite3 node bindings were not properly configured with Windows and Mac. THe issue was fixed by downloading the bindings before packaging.
Closes MES-1

fix(scripts): fix sqlite3 issue with windows binary

---

.dockerignore
Dockerfile

This PR reduces the docker image size by a considerable amount using multistage builds, only having production dependencies on the resulting image and using Alpine Linux as the base image.
|         | Base Image           | Size  |
| ------------- |:-------------| -----:|
| Before      | node:12.13.0 | 1.34GB |
| After      | node:12.13.0-alpine |  405MB |
Closes MES-2

chore(docker): reduce dockerfile resulting image size

---

doc/configuration.md
res/config.json
src/distributed/redis/config.ts
src/distributed/redis/subservice.ts
src/global.ts

This PR adds support for specifying a Redis scope (`REDIS_SCOPE`) which is then used to prefix Redis channels and keys as this prevents messages to be published across every subscribers on a Redis cluster (no matter what DB they subscribed on). See: https://redis.io/topics/pubsub#database-amp-scoping
Closes MES-4

feat(redis): added support to prefix redis channels

---

src/channels/base/channel.ts
src/global.ts
src/launcher.ts
src/logger/types.ts

Closes MES-48
I've made some minor changes to log files just so they fit better with the surrounding logs.
Since we have nlu, studio and messaging, we need to prepend log messages to indicate which process printed that log. The port is "useless" for the end user so i've grayed it, and we don'T need to print the external url since the server already prints it

chore(dev): uniform logging

---

src/channels/base/conduit.ts
src/channels/messenger/conduit.ts
src/channels/slack/conduit.ts
src/channels/smooch/conduit.ts
src/channels/smooch/config.ts
src/channels/teams/conduit.ts
src/channels/telegram/conduit.ts
src/channels/telegram/config.ts
src/channels/twilio/conduit.ts
src/channels/twilio/config.ts
src/channels/vonage/conduit.ts

Closes MES-51
When SPINNED is set, we print the full webhook paths in a friendly way so it makes sense on the botpress console.

feat(logs): log webook path for running conduit

---

src/channels/vonage/conduit.ts

This PR adds support for voice audio reception with Vonage making sure that google-speech still works with this module.
Related to: https://github.com/botpress/studio/pull/33, https://github.com/botpress/botpress/pull/5197 and https://github.com/botpress/botpress/pull/5198
Closes MES-62

feat(vonage): add support for voice audio reception

---

src/channels/base/conduit.ts
src/channels/slack/conduit.ts

This PR adds exception handling when rendering and sending messages on the base channel. And adds error handling with Slack's Event Adapter.
Fixes #26

fix(base): handle exceptions when rendering and sending messages

---

src/channels/twilio/channel.ts

This PR adds support for old webhooks on Twilio by re-constructing the URL that was proxies.
Closes MES-64

fix(twilio): add support for old webhooks

---

src/channels/base/channel.ts
src/channels/base/conduit.ts
src/channels/messenger/channel.ts

This PR adds:
- Handles the case where the provider exists by has no corresponding conduit (e.g. channel is disabled,  and not synced)
- Only display the error message when a sender throw an error (since the error stack may contain Axios' response with sensitive information)
-  Added typings and better logging on the `auth` function that handles payload validation

feat(messenger): improved error handling and logging

---

src/channels/smooch/conduit.ts

This PR adds error handling during the webhook setup. Otherwise, it would crash Messaging if the call fails!

feat(smooch): add error handling during webhook setup

---

src/global.ts
src/instances/service.ts

Multiple botpress nodes would fight in sync calls to set the webhook url to their own respective localhost url. So this PR implements a workaround with the SPINNED_URL env variable that forces a spinned messaging server to do webhook requests to that url instead (so now every spinned messaging node does its webhook requests to the process that spawned it).
Closes MES-71

fix(webhooks): fix url being wrong when spinned from a botrpess cluster

---

.gitignore
packages/client/package.json
packages/client/src/base.ts
packages/client/src/chat.ts
packages/client/src/conversations.ts
packages/client/src/index.ts
packages/client/src/messages.ts
packages/client/src/messaging.ts
packages/client/src/sync.ts
packages/client/src/users.ts
packages/client/tsconfig.json
tsconfig.json

This client is meant to be used has an npm package by the old repo (and any other services) to communicate with messaging. It provides typings for everything
I think a new package should be made to hold typings that are shared between the `client` and the `server` package. It could be called `shared` or `common` and would avoid copy pasting typings from the server to the client (like I did here for example).
PR in main repo https://github.com/botpress/botpress/pull/5209
Closes MES-60

feat(client): implement http client

---

.github/workflows/codestyle.yml

This PR fixes the GitHub actions check that was failing because one of our dependencies required NodeJS >= 12.18.3. See: https://github.com/botpress/messaging/pull/51/checks?check_run_id=3148014125

chore(github): bump github actions nodejs version to 12.18.3

---

packages/server/src/channels/telegram/channel.ts
packages/server/src/channels/telegram/conduit.ts

This PR adds a check to validate the webhook endpoint so that we can be sure all requests come from Telegram.
As per [Telegram's documentation](https://core.telegram.org/bots/api#setwebhook):
> If you'd like to make sure that the Webhook request comes from Telegram, we recommend using a secret path in the URL, e.g. https://www.example.com/<token>. Since nobody else knows your bot's token, you can be pretty sure it's us.
Closes MES-14

feat(telegram): added webhook validation

---

packages/server/src/channels/messenger/channel.ts
packages/server/src/channels/messenger/client.ts
packages/server/src/channels/slack/channel.ts
packages/server/src/channels/slack/conduit.ts
packages/server/src/channels/smooch/channel.ts
packages/server/src/channels/teams/channel.ts
packages/server/src/channels/telegram/channel.ts
packages/server/src/channels/twilio/channel.ts
packages/server/src/channels/vonage/channel.ts

This PR fixes an issue where all routes In messaging add to be defined using router.use because of a misconfiguration of the middleware proxy in the main repo (see: https://github.com/botpress/botpress/pull/5112/commits/035a123b507a3e77369f5ea3631bde2eca5afc95)
Closes MES-41

fix(channels): fix request proxying requiring to use router.use

---

packages/server/src/channels/discord/config.ts
packages/server/src/channels/messenger/config.ts
packages/server/src/channels/slack/config.ts
packages/server/src/channels/smooch/config.ts
packages/server/src/channels/teams/config.ts
packages/server/src/channels/telegram/config.ts
packages/server/src/channels/twilio/config.ts
packages/server/src/channels/vonage/config.ts
packages/server/src/conduits/service.ts
packages/server/src/instances/service.ts
packages/server/src/sync/api.ts
packages/server/src/sync/service.ts

This PR loosens Joi schema validation by discarding unknown properties instead of throwing an error.

fix(channels): loosen joi schema validation by discarding unknown properties

---

packages/server/src/clients/service.ts
packages/server/src/sync/service.ts

This fixes a problem where you could delete a bot in botpress and create a new bot with the same exact id. For most botpress services this bot will be considered to be the same bot because it has the same id. For messaging however the sync call would return a entirely new clientId and would treat it like a completely different client.
This PR changes this behavior so that you get back the same clientId (if possible) so that this new bot is considered to be the same client. We generate a new token for the bot to use with the old client id.
This will solve a problem in our migration. For example right now we create clientIds and tokens for bots that do not exist when running the migration. If someone were to reimport those missing bots, they couldn't access the old conversations of that bot …

fix(sync): assure botId always returns same clientId

---

packages/server/src/health/table.ts

Added a onCascade(delete) to the health events table so foreing key constraints don't fail when a conduit is deleted.
Closes MES-96

fix(health): fix crash when conduit is deleted

---

packages/client/package.json
packages/client/src/messaging.ts
packages/server/src/base/api.ts

This PR fixes an issue where multiple authentication mechanisms could conflict with our basic authentication. We will now need to provide a 'x-bp-messaging-client-*' headers to provide the clientId and clientToken.

fix(auth): use custom headers instead of basic auth

---

packages/server/src/channels/twilio/channel.ts

This PR fixes an issue where having an external URL with a port specified would not allow you to use the old webhooks with Twilio.
Related to: https://github.com/botpress/botpress/pull/5266
Closes https://github.com/botpress/messaging/issues/85

fix(twilio): fix twilio webhooks validation

---

packages/server/src/channels/telegram/conduit.ts

This PR restores the polling feature of telegram so that it can be used in single node environment when spinned from botpress.
Closes MES-99

feat(telegram): restore polling

---

packages/server/src/channels/smooch/conduit.ts

Fixes issue where smooch would produce an error for recreating a webhook that already existed. We also hardcode routes that contain `/mod/channel-smooch` to be deleted to avoid messages being doubled sent
Closes MES-112

fix(smooch): fix webhook setup

---

packages/server/package.json
packages/server/src/distributed/base/subservice.ts
packages/server/src/distributed/local/subservice.ts
packages/server/src/distributed/redis/subservice.ts
packages/server/src/distributed/service.ts
packages/server/src/distributed/types.ts
yarn.lock

Implements locking mechanism using the redlock package (recommended by redis).
The locking works a bit differently than on the main botpress repo. We try taking the lock for about 2 seconds, and if it fails it throws an error.
You can use locking like so :
```ts
// We prefix lock ids with lock_
await this.distributedService.using('lock_my_ressource', async () => {
await doStuff()
await doOtherStuff()
})
```
The code in the callback is mostly guaranteed to only be executed on a single node at once.
Closes MES-102

feat(distributed): implement locking

---

packages/server/src/channels/twilio/channel.ts

This previous fix wasn't working
Fix in main repo https://github.com/botpress/botpress/pull/5269

fix(twilio): fix legacy validation

---

packages/server/src/index.ts

This PR sets the value of NODE_ENV to production when running a binary version of the messaging server.
Closes MES-24

fix(server): run messaging in production when using the binary

---

package.json
packages/server/package.json
packages/server/src/channels/base/channel.ts
packages/server/src/channels/messenger/channel.ts
packages/server/src/channels/messenger/client.ts
packages/server/src/channels/messenger/conduit.ts

It's possible to put anything in the BOT_ID section of the webhook url at the moment and botpress will match the botId using the pageId sent in the body of the requests.
There isn't really a way to handle this on botpress' side so I put some legacy handling code in the messenger channel. It's kind of dirty since the validation needs to be done in two part, because we need the pageId to get the config which is necesarry to validate the request body. The thing is the pageId is in the body, and the body is parsed by the json parser that calls the validate function before parsing the body. So now you have prepareAuth and auth.
Closes MES-120

fix(messenger): fix legacy

---

packages/server/package.json
packages/server/src/post/service.ts
yarn.lock

This PR adds exponentials backoff as the retry strategy for the post service. The default number of attempts is 10, but this could be easily configured. I'm open to ideas/criticism!
The formula for the amount of time it gonna take if the call never resolves is: `100 * 2^(n-1)` (where `n` is the number of retries) 
e.g.
With a [jitter](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/):
Without a jitter:
Closes MES-122

feat(post): added exponential backoff support

---

packages/server/src/channels/messenger/channel.ts

The auth middleware shouldn't be on the webhook verification get route. This caused webhook verification to fail

fix(messenger): fix webhook validation

---

packages/server/src/channels/telegram/conduit.ts

This PR adds a stop call to telegraf when the instance is destroyed. This prevents a bug where a deleted conduit would have an instance that keeps polling messages and tries to receive messages with that conduit.

fix(telegram): destroy telegraf

---

packages/server/src/launcher.ts
packages/server/src/server-manager.ts

This PR adds a check to make sure we manually destroy all the Express server connections when the Messaging server is shutting down.
Should fix the issue where debugging in development mode would result in the debugger port already being taken.
This code is based on libraries recommended by Express to handle graceful shutdowns: https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html

fix(server): added server manager to handle closing server connections

---

.github/workflows/build.yml
Dockerfile

This PR fixes an issue where the @botpress/messaging-base package could not be found due to the way the dockerfile previously built the project.

fix(dockerfile): adapt dockerfile to project references

---

packages/server/src/app.ts
packages/server/src/post/service.ts
packages/server/test/post/service.test.ts

This PR fixes an issue where the post service could still retry multiple times a certain request when the server is shutting down.

fix(post): stop retrying request when server is shutting down

---

packages/server/src/app.ts
packages/server/src/instances/invalidator.ts
packages/server/src/instances/monitoring.ts
packages/server/src/instances/service.ts
packages/server/src/status/service.ts
packages/server/src/status/table.ts

This PR adds the structure for the new status service and makes sure to use this service instead of the in-memory conduit failure count.
Note: This PR creates a new table (msg_status)
Unit tests will be made in another PR.

feat(status): add status service

---

packages/server/src/health/watcher.ts

This adds a `configure` when creating a conduit. That way the `configure` event of health reports all changes in configuration, including the creation of the config.
Closes MES-135

fix(health): send configure event when created

---

packages/server/src/launcher.ts
packages/server/src/socket/manager.ts
packages/server/src/socket/service.ts

This PR makes sure to properly close the websocket server and its connections upon server shutdown.
Closes MES-132

feat(server): gracefully close websocket connections on server shutdown

---

.github/workflows/release.yml
scripts/changelog.js
scripts/release.js

This PR fixes CHANGELOG generation on new release. 
The process is now as follows:
```sh
// Create a new branch from an up-to-date master
git checkout -b vX_X_X
// Run yarn release to bump the package.json version and generate a changelog
yarn release <major|minor|patch>
// Commit the changes and push the branch and create a pull request
git add .
git commit -m "vX_X_X"
git push origin vX_X_X
```
See https://github.com/botpress/messaging/pull/147
Closes MES-37

fix(ci_cd): fix changelog generation on release

---

packages/server/src/post/service.ts
packages/server/test/post/service.test.ts

I my opinion webhook "errors" are not really server errors. So I changed the log status to be warnings.
Closes MES-144

fix(post): log errors as warnings

---

Dockerfile

This PR allows for any users of the Dockerfile to override the command that is passed to the container without having to specify the path to the server's entry point (`./packages/server/src/index.js`).
This way, you can start the container like so:
`docker run -it --rm --name messaging messaging:latest --auto-migrate`

chore(docker): moved all parts of start command to entrypoint

---

packages/server/src/launcher.ts

This PR fixes an issue where Botpress would be terminated and messaging would still run when Botpress is closed because it tries to gracefully shut down.

chore(server): disable graceful shutdown when messaging is spinned from botpress

---

packages/server/src/channels/messenger/conduit.ts

Fixes a problem where having a bot in live mode wouldn't work if it wasn't approved by facebook.
Closes DEV-1950

fix(messenger): fix fetch pageId when in live mode

---

benchmark.sh

Adds a script to benchmark the message creation route.

chore(server): add a benchmark script

---

.github/workflows/docker.yml

The new version of the Docker build action does not require these params

fix(build): unnecessary params for Docker build

---

packages/server/src/stream/service.ts

Renaming a variable name caused the webhooks to break. This PR fixes it

fix(webhook): fix webhooks

---

packages/server/src/instances/monitoring.ts
packages/server/src/instances/service.ts

The timeout for the monitoring wasn't deleted when the server was closes, so now it is.
Closes DEV-1633

fix(monitoring): fix timeout not being cleared

---

packages/engine/src/barrier/barrier.ts
packages/engine/src/barrier/service.ts
packages/engine/src/engine.ts
packages/engine/src/index.ts
packages/server/src/app.ts
packages/server/src/mapping/convmap/service.ts
packages/server/src/mapping/identities/service.ts
packages/server/src/mapping/senders/service.ts
packages/server/src/mapping/service.ts
packages/server/src/mapping/threads/service.ts
packages/server/src/mapping/tunnels/service.ts
packages/server/src/mapping/usermap/service.ts
packages/server/test/mapping.test.ts
packages/server/test/tsconfig.json

It's sometime possible that sometimes the server checks if a mapping exists, and then creates it if it doesn't. If this is done fast enough, it's possible that the check to see if the mapping exists returns false more than once, and the process of creating the mapping starts multiple times. The constraints in the db will prevent more than once request from succeeding, meaning that exceptions will be thrown.
This PR fixes this problem
Closes DEV-1618

fix(mapping): fix insert race conditions

---

packages/engine/src/distributed/redis/subservice.ts

There was a problem when using redis with sentinel, master and slaves where switching a master could make the server crash. The server was set to throw an exception is an attempt to connect failed more than 10 times. I removed this limit so now the server can retry to connect to redis indefinitely.
Closes DEV-2002

fix(redis): fix master failure crashing the server

---

.github/workflows/release.yml

This PR pins the version of the action(s) we use from https://github.com/botpress/gh-actions to `v1`

chore(ci): use botpress shared actions v1

---

packages/server/src/migrations/0.1.20-fix-client-schema.ts
packages/server/src/migrations/index.ts
packages/server/src/sync/service.ts

Fixes a problem in sync calls when messaging is spinned where multiple calls made with the same botId would not be locked. Related https://github.com/botpress/botpress/pull/5760
Closes DEV-2189

fix(sync): add lock for provider name

---

doc/routes.md
packages/client/src/conversations.ts
packages/server/src/conversations/api.ts
packages/server/src/conversations/schema.ts
packages/server/src/conversations/service.ts
packages/server/src/messages/service.ts
packages/server/test/integration/conversations.test.ts
packages/server/test/security/api.test.ts

Removes the /recent route from the conversation api since it can be directly replace by listing the conversations and limiting to 1
Closes DEV-2221

chore(conversations): remove /recent route

---

.github/workflows/release.yml

Basically, if you go see the [releases](https://github.com/botpress/messaging/releases), you'll see that a lot of release notes are missing. This seems to be due to the fact that the variable we passed as body to the release action would strip the changelog because of a `\n` or some other break line. Since the tests made were using this output variable as the body of the release, I take for granted that it will fix the issue.

chore(ci_cd): make sure whole new changelog is passed as body on new releases

---

.yarn/versions/2c52e3b6.yml
CHANGELOG.md
package.json
packages/server/package.json
packages/server/src/launcher.ts

FIxes a bug introduced in #312 that would prevent the server from ever closing when spinned from botpress.

fix(server): fix server not closing when spinned

---

packages/client/src/schema.ts

Since the messaging api might add stuff to its webhook payload, we shouldn't enforce that unknown keys are not present in the payload since this would prevent us in the future from upgrading the messaging api without having to upgrade everything that listens to its events at the same time.
The contract of compatibility with the API user is : when making a request, the data that you were previously sent back will always be sent back, but don't assume that any additional data will not be added to the response in the future. This applies to webhooks as well. We don't guarantee the API user that more data will not be added to the webooks payload, but we assure that the data that was there in the past will still be there.
When making API request, we don't use stripUnknown because it is not …

fix(client): strip unknown data received from webhook

---

packages/server/src/channels/service.ts

This PR removes the experimental channels feature flag so that v1 channels are now enabled by default. This is the first step to enable support for v1 channels inside Botpress.
Note: Will require a new patch release once this is merged.
Related to DEV-2326

feat(channels): remove experimental channels feature flag

---

packages/client/package.json
packages/client/src/base.ts
packages/client/src/channel.ts
packages/client/src/logger.ts
packages/client/src/options.ts
packages/server/src/api.ts
packages/server/src/base/api/utils.ts
packages/server/src/base/streamer.ts
packages/server/test/security/api.test.ts
packages/socket/test/e2e/socket.test.ts

Adds /v1 to API paths. Is backward compatible with not using /v1. Will require a new release of the http client.
Also should we version the socket connection? Right now the socket connects at the root of our url. Maybe it could connect at `/sockets/v1`?
The client package needs to be updated
Closes DEV-2285
Closes DEV-2323

chore(api): add /v1 to api paths

---

.gitignore
packages/inject/package.json
yarn.lock

This PR fixes an issue with the inject package that is related to the way parcel outputs scripts source in the resulting index.html. This was fixed by adding the `--public-url` argument.
It also adds a bundler analyzer so we can inspect the space taken by each dep in the resulting bundle.

fix(inject): fix inject script public path

---

docs/routes.md
misc/api.rest
packages/base/src/endpoint.ts
packages/base/src/index.ts
packages/client/src/api.ts
packages/client/src/client.ts
packages/client/test/e2e/client.test.ts
packages/server/src/api.ts
packages/server/src/mapping/api.ts
packages/server/src/mapping/schema.ts
packages/server/test/security/api.test.ts

Adds two new routes that make up the "endpoint" API. One route `/endpoints/map` to get a conversationId from an endpoint, and the route `/endpoints/conversation/:conversationId` to list the endpoints associated to a conversation (since a conversation can be present on more than one channel)
TODO: add documentation
Closes DEV-2339

feat(mapping): endpoint api

---

packages/components/package.json
packages/inject/package.json
packages/webchat/package.json
yarn.lock

Bumps and published all packages related to webchat to version 0.2.0. Also updated the cdn. We can now see what version of the webchat is deployed at : https://cdn.botpress.dev/webchat/v0/version.json (version should match versions deployed on npm)

chore(webchat): bump to 0.2.0

---

.github/workflows/build.yml
.github/workflows/codestyle.yml
.github/workflows/release.yml
.github/workflows/tests.yml

This PR updates the Github Actions to use the version of NodeJS specified in the .nvmrc file instead of a hard-coded version.

chore(ci): use nvmrc version instead of hard coded

---

packages/server/package.json
yarn.lock

Fixes a problem where channels would print their webhooks with the name in it twice (so for example twilio would print externalUrl/webhooks/botId/twilio/twilio)
Commit in v1 https://github.com/botpress/messaging/commit/030a8a3699f3e024db9b5d95519de7d2cea22fa2

fix(channels): logging incorrect webhook for channel legacy

---

packages/webchat/src/core/api.tsx
packages/webchat/src/main.tsx
packages/webchat/src/store/index.ts
packages/webchat/src/typings.ts

This PR removes the already broken concept of conversation references. As this was to address security concerns but isn't required anymore with the messaging socket implementation and security measures we have.
Closes DEV-2305

chore(webchat): remove the concept of reference

---

.github/workflows/upload.yml

This PR adds a temporary invalidation step to the action that uploads the webchat so that we are sure the CDN always provides the latest version of the webchat bundle. I also added the [`--delete`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html) argument to the upload call so that we delete old files if needed. Finally, we only deploy the webchat if there were changes in any files related to it.

chore(ci_cd): add tmp invalidation step when uploading webchat

---

packages/server/src/socket/manager.ts

Fixes bug reported here https://botpresshq.slack.com/archives/C02AFENA9C5/p1646837902625429
The code for socket message handling had a try catch, but the code located in the catch could also throw, so I added a try catch there also.
Closes DEV-2425

fix(sockets): fix socket unable to send error message crashing server

---

.github/workflows/upload.yml

This PR removes the cache invalidation step from the webchat upload action since the permission to do so was removed.

chore(ci_cd): remove cache invalidation step from webchat upload

---

misc/api.rest
packages/components/package.json
packages/components/src/css/botpress-default.css
packages/components/src/renderer/index.tsx
packages/components/src/renderer/location.tsx
packages/components/src/typings.ts
packages/webchat/src/components/messages/Message.tsx
packages/webchat/src/typings.ts
yarn.lock

This PR adds the location component and enables its support on the webchat.
It requires a Google Maps API Key to be set in the webchat config: https://developers.google.com/maps/documentation/javascript/get-api-key
**api.rest** 
```
POST {{baseUrl}}/api/v1/messages
Authorization: Bearer {{authToken}}
x-bp-messaging-client-id: {{clientId}}
x-bp-messaging-client-token: {{clientToken}}
Content-Type: application/json
{
"conversationId": "{{convoId}}",
"payload": {
"type": "location",
"latitude": -25.363,
"longitude": 130.044,
"title": "",
"address": "Uluru (Ayers Rock)"
}
}
```

feat(components): added location component

---

.github/workflows/create-release-pr.yml
.github/workflows/release.yml
package.json
packages/server/package.json

This PR adds an action ("Create Release Pull Request") whose task is to automate the creation of the release PR. It also allows us to bump the version of the root package.json while working in the next version without automatically releasing a new binary. 
Also closes DEV-2233

chore(ci_cd): added action to create release

---

.github/workflows/create-release-pr.yml
.github/workflows/release.yml

This PR updates the actions from `gh-actions` to its latest version v2.
Note: next was simply merged into v2

chore(ci_cd): use gh-actions v2

---

packages/channels/src/messenger/senders/typing.ts

This PR fixes an issue with messenger when the typing indicates would display wierdly
**Before**
https://user-images.githubusercontent.com/9640576/159575117-45cd1b8d-d301-4453-9b07-6a5d504b7429.mp4
**After**
https://user-images.githubusercontent.com/9640576/159574896-7b1bed39-563f-4640-9da7-07d4765d3304.mp4

fix(messenger): remove flaky typing off event

---

packages/server/test/migration/global-diff.test.ts
packages/server/test/migration/migration-cli.test.ts
packages/server/test/migration/migrations-diff.test.ts
packages/server/test/migration/utils/database.ts
packages/server/test/migration/utils/semver.ts
packages/server/test/migration/utils/server.ts

Self-explanatory. We cover all the unhappy and happy paths that a user can take when interfacing with the migration CLI.
Here are the options: 
- `--auto-migrate`
- `migrate <up|down> [--target <target>] [--dry]`

chore(tests): add migration cli tests

---

package.json
packages/base/package.json
packages/base/src/endpoint.ts
packages/client/package.json
packages/client/src/schema.ts
packages/inject/package.json
packages/server/package.json
packages/server/src/base/source.ts
packages/server/src/base/streamer.ts
packages/server/src/conversations/stream.ts
packages/server/src/instances/messaging/service.ts
packages/server/src/mapping/api.ts
packages/server/src/mapping/schema.ts
packages/server/src/mapping/service.ts
packages/server/src/mapping/tunnels/service.ts
packages/server/src/mapping/tunnels/table.ts
packages/server/src/mapping/tunnels/types.ts
packages/server/src/messages/api.ts
packages/server/src/messages/stream.ts
packages/server/src/migrations/1.1.7-custom-channels.ts
packages/server/src/migrations/index.ts
packages/server/test/integration/mapping.test.ts
packages/socket/package.json
packages/webchat/package.json
yarn.lock

Adds a way to create mappings for any arbitrary string. The channel part of the endpoint doesn't have to be a predefined channel anymore
For a full demo of how to use this feature see : https://github.com/botpress/custom-channel
Closes DEV-2397

feat(channels): custom channels

---

.github/workflows/docker.yml

Self-explanatory. This fixes a problem where we had to manually run the action when a new release was published to have an image deployed with the new tag.

chore(ci_cd): allow pushing docker image when release is published

---

packages/server/test/migration/global-diff.test.ts
packages/server/test/migration/migration-cli.test.ts
packages/server/test/migration/migrations-diff.test.ts
packages/server/test/migration/utils/error.ts
packages/server/test/migration/utils/server.ts
packages/server/test/utils/index.ts

This PR improves the migration tests by using services directly instead of using the CLI for each test. This improves the speed of global and migration diff tests by a factor of at least 15. 
I also improve the time it takes to run the CLI test by having a step that builds the server before running. This change removes the unnecessary call to `yarn start` each time we interact with the CLI.

chore(tests): use services instead of cli

---

packages/client/test/e2e/client.test.ts
packages/server/test/security/api.test.ts
packages/socket/test/e2e/socket.test.ts
test/jest.e2e.setup.ts

This PR changes the E2E test setup so that we don't rely on a hard-coded port number but instead use a random unused port.
This allows us to have a running messaging server when running tests without having it conflict with them.

chore(tests): use random unused port for e2e tests

---

package.json
packages/server/package.json
packages/server/src/billing/service.ts
packages/server/src/global.ts
packages/server/src/socket/manager.ts

Prevents everything happening with sockets from being logged to the console
Also adds ENABLE_BILLING_STATS to get logging for amount of messages received, sent even if BILLING_ENDPOINT is not set
Closes DEV-2583

chore(socket): don't log every socket event

---

packages/server/test/security/http.test.ts
packages/server/test/security/socket.test.ts
test/setup/server.ts

This PR adds non-regression security tests for the Socket API.
Note that I also renamed our current API test to HTTP so that we can easily differentiate HTTP tests for Socket ones.

chore(tests): add security tests for socket api

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.github/workflows/upload-webchat-production.yml
.github/workflows/upload-webchat-staging.yml
Dockerfile
packages/messaging/server/test/migration/migration-cli.test.ts
packages/studio/frontend/src/index.tsx
packages/studio/frontend/src/views/CodeEditor/components/SplashScreen.tsx
test/setup/server.ts

This PR:
- Make sure that we point to the right folders in the workflows related to the webchat.
- Convert the yarn build script that used to point to the messaging-server package to call it directly.
- Updated the test job to only run when needed.

chore(ci_cd): adapt ci with changes make on yarn scripts and folder structure

---

.github/workflows/build.yml

This PR renamed some jobs and steps so that we use a more consistent naming across all our actions.

chore(ci_cd): small ci overall improvements

---

packages/studio/frontend/src/index.tsx
packages/studio/server/src/studio/server.ts

Self-explanatory. We don't want the port of the runtime and studio server to conflict.

chore(studio): use port 3300 for studio server

---

packages/channels/src/messenger/api.ts
packages/channels/src/messenger/messenger.ts

This PR adds support for receiving file content-elements (audio, video, images, pdf, etc...) with Messenger _(channel v1.0.0 only)._

feat(messenger): allow receiving file content elements

---

packages/studio/server/src/studio/studio-router.ts
packages/studio/server/src/studio/testing/index.ts
packages/studio/server/src/studio/testing/recorder.ts
packages/studio/server/src/studio/testing/runner.ts
packages/studio/server/src/studio/testing/testing-router.ts
packages/studio/server/src/studio/testing/testing-service.ts
packages/studio/server/src/studio/testing/typings.ts
packages/studio/server/src/studio/testing/utils.ts

This PR re-adds the testing module backend to the Studio Server. 
As you will see, I added a lot of TODOs and commented out some pieces of code. This is because we will need to have some ways of querying the runtime to fetch this missing info. I don't think, for example, that the studio should have a direct connection to the runtime's database.

chore(studio): re-add testing router

---

.github/workflows/release.yml

This PR adds the v1.2 branch as a trigger for releasing a new version of messaging LTS (v.1.2.X)

chore(ci_cd): allow releasing messaging LTS (v.1.2) versions

---

.github/workflows/release.yml

Self-explanatory. We want to be able to manually release a new version and allow to release versions from the v1.2 branch.

chore(ci_cd): allow manually releasing a new version

---

.yarnrc.yml

This PR removes some verbose logging from yarn commands like printing all the warnings about peer dependencies, build, cache entries, etc.
To test this PR, run `yarn` after upgrading a package, adding a new one, removing a package, adding one that does not exist, etc.

chore(yarn): remove unnecessary log outputs

---

.github/workflows/build.yml
.yarnrc.yml
packages/studio/frontend/package.json
packages/studio/frontend2/package.json
packages/studio/server/package.json
yarn.lock

This PR adds some small overall improvements to the repo by:
- Renaming the studio-be package to studio-server
- Renaming the studio-ui package to studio-frontend
- Fixing a dependency issue with i18next-browser-languagedetector
- And adding another entry to the logFilter list in the yarnrc file.

chore: small overall improvements

---

packages/framework/src/routes.ts
packages/server/test/security/api.test.ts

Self-explanatory!
Note that we don't care if the max payload size is 100kb or 150kb as long as it's a reasonable size for text payloads. 150kb is also the max payload size of MS Teams.

chore(server): increase max payload size to 150kb

---

packages/webchat/src/components/messages/Message.tsx
packages/webchat/src/components/messages/MessageGroup.tsx
packages/webchat/src/core/socket.tsx
packages/webchat/src/main.tsx
packages/webchat/src/store/index.ts
packages/webchat/src/store/view.ts
packages/webchat/src/utils/webchatEvents.ts

This PR allows the developer to react to message click on the webchat. When a user clicks on any message, an event (`messageClicked`) is sent to the parent windows (the HTML page that embeds the webchat) that contains the message details.

feat(webchat): allow to react on message click

---

packages/channels/src/telegram/README.md
packages/channels/src/telegram/api.ts

This PR adds support for receiving files (file/audio/video/image) with Telegram (channel v1.0.0 only).
Similar to: https://github.com/botpress/messaging/pull/480

feat(telegram): allow receiving file/audio/video/image

---

packages/components/src/css/botpress-default.css
packages/webchat/package.json
packages/webchat/src/components/messages/MessageList.tsx
packages/webchat/src/declaration.ts
yarn.lock

This adds the changes from https://github.com/botpress/botpress/pull/12193 to the webchat
Also includes the fix from https://github.com/botpress/botpress/pull/12178

fix(webchat): inconsistent scrolling behavior

---

.github/workflows/tests.yml
package.json
packages/inject/src/inject.test.ts
packages/inject/src/inject.ts
packages/inject/test/cssmock.js
packages/inject/test/tsconfig.json
test/jest.inject.config.ts

Pretty sure the error is related to the "isWebchatEvent" function... It was really too basic.
These event causes those errors:
Still need a way to test them correctly, since stratus uses the CDN, I didn't test "strictly", but logic looks fine.

fix(messaging): fix inject error
