botpress/messaging

README.md
doc/configuration.md
src/launcher.ts

This PR speaks for itself!
Closes MES-3

chore(doc): small improvements + typos

---

package.json
src/base/api.ts
src/channels/base/channel.ts
src/channels/service.ts
src/channels/table.ts
src/channels/telegram/channel.ts
src/conduits/service.ts
src/instances/invalidator.ts

Self-explanatory
Closes MES-22

fix(channels): renamed initable column to initiable + typos

---

doc/configuration.md
res/config.json
src/global.ts
src/instances/service.ts

Allows to disable logging for incoming and outgoing messages.
Closes MES-11

feat(logger): toggle disable

---

src/channels/telegram/renderers/text.ts

Related to: https://github.com/botpress/botpress/pull/5173

fix(telegram): fix markdown rendering in telegram

---

src/channels/teams/channel.ts
src/channels/teams/conduit.ts
src/channels/teams/config.ts

This PR adds support for proactive messages with Teams
Closes MES-6

feat(channel-teams): add support for proactive messages

---

src/instances/service.ts

This PR adds password validation to the on receive webhooks
Related to https://github.com/botpress/botpress/pull/5167/commits/672e6a4a66cb44fcbb129e361afcd2ac4e2dd81c
Closes MES-28

feat(core): send password to webhooks on receive

---

src/channels/base/conduit.ts
src/global.ts

Self-explanatory
Related to https://github.com/botpress/botpress/pull/5182
Closes MES-9

feat(core): use BOTPRESS_EXTERNAL_URL as botUrl

---

src/chat/api.ts
src/instances/service.ts

Fixes to make the debugger work in the studio.
PR on botpress repo : https://github.com/botpress/botpress/pull/5183
PR on studio repo : https://github.com/botpress/studio/pull/30
Closes MES-30

feat(messaging): return created message to sender

---

src/caching/service.ts
src/channels/base/conduit.ts
src/channels/twilio/conduit.ts
src/channels/twilio/context.ts
src/channels/twilio/renderers/choices.ts
src/channels/vonage/conduit.ts
src/channels/vonage/context.ts
src/channels/vonage/renderers/carousel.ts
src/channels/vonage/renderers/choices.ts
src/channels/vonage/types.ts
src/kvs/service.ts

This PR brings back the support for index responses as it was in the main repository when using Twilio and Vonage.
Closes MES-5

feat(channels): add support for index responses with twilio and vonage

---

src/channels/smooch/channel.ts
src/channels/smooch/conduit.ts
src/channels/smooch/config.ts

Some stuff was still left commented out in the smooch channel so I finished the job.
Closes MES-16

fix(smooch): fix unfinished code

---

src/api.ts
src/app.ts
src/channels/web/channel.ts
src/conduits/service.ts
src/sync/api.ts
src/sync/schema.ts
src/sync/service.ts

feat(channels): validate channel configs

---

src/app.ts
src/global.ts
src/instances/invalidator.ts
src/instances/monitoring.ts
src/instances/service.ts
src/launcher.ts

feat(channels): allow to globally disable lazy loading

---

src/channels/base/channel.ts

This PR adds an extra layer of validation to only process requests that match a provider and raise an error otherwise.
Fixes #27

fix(base): handle provider not found

---

src/channels/base/channel.ts
src/channels/teams/channel.ts

feat(teams): improved asyncMiddleware and typings

---

src/channels/vonage/channel.ts
src/channels/vonage/senders/common.ts

feat(vonage): improved typings

---

src/channels/twilio/channel.ts

feat(twilio): improved logging when request validation fails

---

src/instances/service.ts

fix(conduits): fix the server crashing when a conduit is misconfigured

---

src/channels/telegram/renderers/carousel.ts

This PR improves card rendering with Telegram.
Related to https://github.com/botpress/botpress/pull/5204

feat(telegram): improved card rendering

---

packages/server/src/channels/base/renderers/dropdown.ts
packages/server/src/channels/discord/conduit.ts
packages/server/src/channels/messenger/conduit.ts
packages/server/src/channels/slack/conduit.ts
packages/server/src/channels/slack/renderers/dropdown.ts
packages/server/src/channels/slack/renderers/index.ts
packages/server/src/channels/smooch/conduit.ts
packages/server/src/channels/telegram/conduit.ts
packages/server/src/channels/twilio/conduit.ts
packages/server/src/channels/vonage/conduit.ts

WIP
This PR reads dropdown support for all channels.
Closes MES-21

chore(channels): dropdown support

---

packages/server/src/channels/base/conduit.ts
packages/server/src/channels/base/context.ts
packages/server/src/channels/twilio/conduit.ts
packages/server/src/channels/twilio/context.ts
packages/server/src/channels/twilio/renderers/carousel.ts
packages/server/src/channels/twilio/renderers/choices.ts
packages/server/src/channels/vonage/conduit.ts
packages/server/src/channels/vonage/context.ts
packages/server/src/channels/vonage/renderers/carousel.ts
packages/server/src/instances/service.ts

This PR does some fixes on the twilio channel :
- It sends an message of type `quick_reply` for choices
- It sends a message of type `postback` for postback buttons
- It sends a message of type `say_something` for say something buttons
- It sends nothing for open url messages
Closes  MES-18

fix(twilio): fix buttons

---

packages/server/src/channels/slack/conduit.ts
packages/server/src/channels/slack/renderers/carousel.ts
packages/server/src/channels/slack/renderers/choices.ts

fix(slack): fix say something

---

packages/server/src/channels/messenger/conduit.ts
packages/server/src/channels/messenger/renderers/carousel.ts

fix(messenger): fix say something

---

packages/server/src/sync/schema.ts

This PR fixes https://github.com/botpress/messaging/issues/56

fix(sync): strip unknown properties when syncing

---

packages/server/src/instances/service.ts

To awaiting this call here was causing the issue
Closes MES-65

fix(messages): fix wait times between messages

---

packages/server/src/api.ts

This PR adds a basic status check endpoint.
Closes MES-78

feat(api): add status check

---

Dockerfile
packages/server/src/api.ts

Self-explanatory for the Dockerfile part and changes the status check response code to 200.

fix(dockerfile): adapt dockerfile to work with yarn workspaces

---

packages/server/src/instances/invalidator.ts
packages/server/src/instances/monitoring.ts
packages/server/src/instances/service.ts

#68
This will enventually be replaced by a `HealthService` and `LifetimeService` that will provide history and diagnostics for conduits
Closes MES-84

fix(instance): stop retrying setup after 5 attemps

---

packages/server/src/api.ts
packages/server/src/app.ts
packages/server/src/base/events.ts
packages/server/src/caching/cache.ts
packages/server/src/caching/cache2D.ts
packages/server/src/database/service.ts
packages/server/src/health/api.ts
packages/server/src/health/service.ts
packages/server/src/health/table.ts
packages/server/src/health/types.ts
packages/server/src/health/watcher.ts
packages/server/src/instances/events.ts
packages/server/src/instances/invalidator.ts
packages/server/src/instances/monitoring.ts
packages/server/src/instances/service.ts

Implements a health service that allows the api user to track the state of their configured channels.
Closes MES-82

feat(health): implement health service

---

packages/server/src/health/service.ts
packages/server/src/instances/service.ts

This PR adds the mechanism to send the webhook token for validation by users of webhooks.
Closes MES-8
Related to: https://github.com/botpress/botpress/pull/5241

feat(webhook): added possibility to send webhook token for validation

---

packages/client/src/health.ts
packages/client/src/messaging.ts

Usage
```ts
const health = await client.health.get()
```
Closes MES-91

feat(client): health client

---

packages/server/package.json
packages/server/src/api.ts

Self-explanatory
Closes MES-94

feat(api): added endpoint to query server version

---

packages/server/src/health/service.ts
packages/server/src/instances/service.ts

Fixes problem with SPINNED env variable

fix(webhook): add forgotten yn

---

packages/server/src/channels/twilio/channel.ts

We can use the host header instead of having to pass the BOT_URL as environment variable.
Closes MES-95
Related to: https://github.com/botpress/botpress/pull/5237

fix(twilio): removed unnecessary bot url for webhook validation

---

packages/client/package.json
packages/client/src/messaging.ts

Make sure to handle the case where no password or auth is provided to the client.

fix(client): fix initializing a client with not auth or password

---

packages/server/src/health/watcher.ts
packages/server/src/instances/monitoring.ts
packages/server/src/instances/service.ts
yarn.lock

Puts a try catch somewhere where it was needed and fixes some other issues

fix(crash): more failsafe

---

packages/client/package.json
packages/client/src/messaging.ts

Implement same auth as base PR

feat(client): use headers to provide clientId and clientToken

---

packages/server/src/kvs/service.ts

fix(kvs): fix json

---

packages/server/res/config.json
packages/server/src/health/service.ts
packages/server/src/instances/service.ts
packages/server/src/webhooks/broadcaster.ts

This PR put all the duplicated to that was used to call webhooks into one class.

feat(webhook): common sender class

---

api.rest
doc/routes.md

Was mostly outdated due to changes in how auth works.

chore(repo): update doc and api.rest

---

.vscode/launch.json
.vscode/settings.json
packages/server/jest.config.js
packages/server/package.json
packages/server/src/post/service.ts
packages/server/tests/post/service.test.ts
yarn.lock

This PR adds unit tests for the post service and adds a launch config for debugging unit tests.

chore(post): added unit tests for post service

---

package.json
packages/server/package.json
packages/server/src/health/service.ts
packages/server/src/instances/service.ts

fix(webhooks): don't await webhooks

---

packages/server/src/config/service.ts
packages/server/test/config/service.test.ts
packages/server/test/database/service.test.ts
packages/server/test/logger/types.test.ts
packages/server/test/post/service.test.ts

chore(tests): refactored unit tests

---

.github/workflows/build.yml
packages/server/src/messages/api.ts

This PR adds a PR check to make sure everything builds properly
Fixes a path change that was forgotten here: https://github.com/botpress/messaging/pull/129

chore(ci_cd): add step to build the project

---

package.json
packages/server/package.json

Bumps server version to v0.1.8

chore(server): v0.1.8

---

packages/board/src/app.ts
packages/board/src/linker.ts
packages/socket/src/com.ts

Adds a field to the board the allows changing the host of the webchat in the ui instead of having to do it in the code.

feat(board): host url field

---

packages/server/src/instances/service.ts

fix(instances): fix instance service destroy

---

packages/server/src/chat/service.ts

fix(chat): fix crash when replying to null conduit

---

CHANGELOG.md
package.json
packages/server/package.json

chore(messaging): v0.1.10

---

CHANGELOG.md
package.json
packages/server/package.json

Bumps messaging server to 0.1.12

chore(server): v0.1.12

---

CHANGELOG.md
package.json
packages/server/package.json

* **apm:** added apm configuration setup ([#167](https://github.com/botpress/messaging/issues/167)) ([a1cc6a0](https://github.com/botpress/messaging/commit/a1cc6a07eda7be1e9245a53951c61a2e03ed635a))
* **webhook:** add convo and user events ([#168](https://github.com/botpress/messaging/issues/168)) ([2e30ddd](https://github.com/botpress/messaging/commit/2e30ddd60807f61332c1f519e269143fbb1ca18a))

chore(dev): v0.1.13

---

packages/server/src/channels/smooch/channel.ts
packages/server/src/channels/smooch/conduit.ts
packages/server/src/channels/smooch/context.ts
packages/server/src/channels/smooch/renderers/carousel.ts

Closes DEV-1625
Fixes postback and say something buttons on smooch

fix(smooch): fix buttons

---

packages/server/src/channels/messenger/conduit.ts
packages/server/src/channels/smooch/channel.ts
packages/server/src/channels/smooch/conduit.ts
packages/server/src/channels/smooch/context.ts
packages/server/src/channels/smooch/renderers/carousel.ts

Head branch of team shake_your_botpress
Members of the team are: 
- @franklevasseur 
- @samuelmasse 
- @daukadolt 
- @crochcunill
Bug fixes:
- fix(messenger): fix fetch pageId when in live mode (**2pts**)
- fix(smooch): fix buttons (**2pts**)
**DO NOT SQUASH THIS BRANCH**

fix(channels): fixes for smooch and messenger

---

CHANGELOG.md
package.json
packages/server/package.json

chore(messaging): v0.1.17

---

packages/components/package.json

simply bump package version to 0.0.2

chore(components): bump version

---

.dockerignore
Dockerfile

This PR fixes the docker image so that the server can find the files for the engine package.

fix(docker): fix path to engine package files

---

packages/board/src/linker.ts
packages/chat/package.json
packages/chat/src/chat.ts
packages/chat/src/user/system.ts
packages/server/src/socket.ts
packages/server/src/socket/manager.ts
packages/server/src/socket/schema.ts
packages/server/src/socket/service.ts
packages/server/src/users/schema.ts
packages/server/src/users/socket.ts
packages/socket/package.json
packages/socket/src/com.ts
packages/socket/src/socket.ts
packages/webchat/package.json
packages/webchat/src/core/socket.tsx

Requires that authentication be provided when a user connects to a socket. A socket connection can no longer be held without first authenticating a user.
We'll need to bump the socket package version before merging this
Closes DEV-2074

feat(socket): authenticate in handshake

---

CHANGELOG.md
package.json
packages/server/package.json

Bumps server version to v0.1.18

chore(server): v0.1.18

---

CHANGELOG.md
package.json
packages/server/package.json

Bump to node 16 and monitoring fix

chore(server): v0.1.19

---

packages/server/src/channels/base/conduit.ts
packages/server/src/channels/teams/conduit.ts
packages/server/src/stream/service.ts

Adds a conversation.started event that allows sending a proactive message
Closes DEV-1623
Closes DEV-2070

feat(channels): add conversation.started event

---

packages/engine/src/database/service.ts
packages/engine/test/unit/database.test.ts

Added missing unit tests for database class

chore(tests): added unit tests for database class

---

packages/engine/src/database/service.ts
packages/engine/test/unit/batcher.test.ts
packages/engine/test/unit/database.test.ts

chore(tests): added unit tests for batcher classes

---

.vscode/launch.json
packages/server/src/socket/manager.ts
packages/socket/src/com.ts
packages/socket/src/emitter.ts
packages/socket/src/socket.ts
packages/socket/test/e2e/socket.test.ts
test/jest.e2e.setup.ts

This PR improves the E2E tests for the socket client
Closes DEV-2055

chore(tests): improved e2e tests for socket client

---

.yarn/versions/f8924e65.yml
CHANGELOG.md
package.json
packages/base/package.json
packages/board/package.json
packages/channels/package.json
packages/client/package.json
packages/components/package.json
packages/engine/package.json
packages/inject/package.json
packages/server/package.json
packages/socket/package.json
packages/webchat/package.json
yarn.lock

Patch release that contains changes to the clients, sync call and test suites

chore(server): v0.1.22

---

.yarn/versions/6e28d4fc.yml
packages/client/package.json
packages/client/src/base.ts
packages/client/src/client.ts
packages/client/test/e2e/client.test.ts
packages/server/src/launcher.ts

This PR adds the capacity to change options passed to the http client after it was created in the constructor.

feat(client): allow to modify options dynamically

---

.yarn/versions/2c52e3b6.yml
.yarn/versions/6e28d4fc.yml
.yarn/versions/85495e24.yml
.yarn/versions/f8924e65.yml
CHANGELOG.md
package.json
packages/base/package.json
packages/board/package.json
packages/channels/package.json
packages/client/package.json
packages/components/.npmignore
packages/components/package.json
packages/engine/package.json
packages/inject/package.json
packages/server/package.json
packages/socket/package.json
packages/webchat/package.json
yarn.lock

chore(server): v1.0.0

---

packages/channels/src/base/meta.ts
packages/channels/src/messenger/channel.ts
packages/channels/src/messenger/config.ts
packages/channels/src/slack/channel.ts
packages/channels/src/slack/config.ts
packages/channels/src/smooch/channel.ts
packages/channels/src/smooch/config.ts
packages/channels/src/teams/channel.ts
packages/channels/src/teams/config.ts
packages/channels/src/telegram/channel.ts
packages/channels/src/telegram/config.ts
packages/channels/src/twilio/channel.ts
packages/channels/src/twilio/config.ts
packages/channels/src/vonage/channel.ts
packages/channels/src/vonage/config.ts
packages/server/src/channels/api.ts
packages/server/src/channels/service.ts
packages/server/src/channels/table.ts
packages/server/src/conduits/service.ts
packages/server/src/migrations/1.0.2-channel-versions.ts
packages/server/src/migrations/index.ts
packages/server/src/sync/api.ts
packages/server/src/sync/schema.ts
packages/server/src/sync/service.ts
packages/server/test/integration/conduits.test.ts
packages/server/test/integration/health.test.ts
packages/server/test/integration/mapping.test.ts
packages/server/test/integration/status.test.ts
packages/server/test/unit/sync.test.ts

Adds versioning to our channels. It's not possible for a single clientId to have more than one version of the same channel configured at the same time (by design).
Closes DEV-2261

feat(channels): channel versioning

---

CHANGELOG.md
package.json
packages/channels/package.json
packages/server/package.json

Patch for channels table migration. Also bumps channels package to 0.1.1

chore(server): v1.0.2

---

packages/server/src/conversations/stream.ts
packages/server/src/messages/stream.ts

Really minor change to the streamer. I reordered the values to make more sense

chore(server): reorder some stuff

---

.yarn/versions/495bd84d.yml
CHANGELOG.md
package.json
packages/server/package.json

chore(server): v1.0.3

---

misc/api.rest
packages/client/package.json
packages/client/src/api.ts
packages/client/test/e2e/client.test.ts
packages/server/src/clients/api.ts
packages/server/src/clients/schema.ts

feat(clients): allow specifying a custom client id

---

CHANGELOG.md
docs/routes.md
misc/api.rest
misc/benchmark.sh
package.json
packages/server/package.json

Also changed some /v1 that weren't added at some places

chore(server): v1.0.6

---

packages/components/src/css/botpress-default.css

This PR fixes the display of file content (audio, video, and images).
**Screenshot**
Closes DEV-2296, DEV-2297, and DEV-2298

chore(webchat): fix display of file content

---

packages/components/src/css/botpress-default.css
packages/components/src/renderer/carousel.tsx

This PR fixes the display of the carousel in the webchat to have the exact same behavior as we have on the channel-web.
**Screen recording**
https://user-images.githubusercontent.com/9640576/153934421-a97d278d-7c3c-4cb5-a039-42deb66644a6.mp4
Closes DEV-2295

chore(webchat): fix display of carousel

---

packages/server/src/conversations/schema.ts
packages/server/src/conversations/socket.ts
packages/socket/src/socket.ts
packages/webchat/src/core/api.tsx
packages/webchat/src/store/index.ts

Webchat now sends a conversation.started even when it creates a conversation.
Closes DEV-2309

feat(webchat): send conversation.started event

---

packages/inject/README.md
packages/server/src/global.ts
packages/server/src/migrations/1.1.0-user-tokens.ts
packages/server/src/migrations/index.ts
packages/server/src/socket/manager.ts
packages/server/src/user-tokens/service.ts
packages/server/test/integration/client-tokens.test.ts
packages/server/test/integration/user-tokens.test.ts
test/jest.e2e.setup.ts

Enables sockets by default. Adds a DISABLE_SOCKET option to disable sockets
Closes DEV-2352

feat(sockets): enable sockets by default

---

packages/server/src/channels/service.ts
packages/server/src/global.ts
packages/server/test/integration/conduits.test.ts
packages/server/test/integration/health.test.ts
packages/server/test/integration/mapping.test.ts
packages/server/test/integration/status.test.ts
packages/server/test/migration/0.1.19-status.test.ts
packages/server/test/unit/sync.test.ts

Makes it so legacy channels are disabled by default, and need to be enabled with ENABLE_LEGACY_CHANNELS
Closes DEV-2353

feat(channels): disable legacy channels by default

---

CHANGELOG.md
package.json
packages/base/package.json
packages/client/package.json
packages/engine/package.json
packages/server/package.json
packages/socket/package.json
packages/webchat/package.json
yarn.lock

Also released 1.1.0 for base, client and socket packages

chore(server): v1.1.0

---

packages/channels/src/base/api.ts
packages/channels/src/teams/api.ts
packages/server/package.json
packages/server/src/base/auth/base.ts
yarn.lock

Also need to prevent the server from crashing when sending two reponses to a http request
Related changes on v1 : https://github.com/botpress/messaging/commit/f485ae270904a624d49e8aab1e7a2c2716935d3f
Fixes https://github.com/botpress/messaging/issues/369
Closes DEV-2358

fix(teams): error crashing server

---

misc/api.rest

chore(dev): added some missing content-types to rest.api file

---

misc/api.rest
packages/components/src/css/botpress-default.css
packages/components/src/typings.ts
packages/components/src/utils.ts
packages/inject/src/inject.css
packages/webchat/src/components/Composer.tsx
packages/webchat/src/components/Container.tsx
packages/webchat/src/components/ContextMenu.tsx
packages/webchat/src/components/Header.tsx
packages/webchat/src/components/messages/Message.tsx
packages/webchat/src/components/messages/MessageGroup.tsx
packages/webchat/src/components/messages/MessageList.tsx
packages/webchat/src/core/api.tsx
packages/webchat/src/main.tsx
packages/webchat/src/store/index.ts
packages/webchat/src/store/view.ts
packages/webchat/src/typings.ts
packages/webchat/src/utils.tsx

This PR aims at removing all code related to the emulator.
Closes DEV-2307

chore(webchat): removed emulator related code

---

packages/channels/src/messenger/README.md
packages/channels/src/slack/README.md
packages/channels/src/smooch/README.md
packages/channels/src/teams/README.md
packages/channels/src/telegram/README.md
packages/channels/src/twilio/README.md
packages/channels/src/vonage/README.md
packages/channels/src/vonage/renderers/carousel.ts

This PR adds versions to the channels README and information about which content-element is down rendered on which channel.

chore(channels): add version and down rendering info to channels readme

---

README.md
packages/client/README.md
packages/client/package.json
packages/client/src/api.ts
packages/client/src/auth.ts
packages/client/src/base.ts
packages/client/src/channel.ts
packages/client/src/client.ts
packages/client/src/events.ts
packages/client/src/logger.ts
packages/client/src/schema.ts

Adds documentation for the @botpress/messaging-client packages and badges in the root readme.
Closes DEV-1939

chore(client): documentation

---

packages/inject/package.json

chore(inject): v0.2.5

---

packages/webchat/README.md

chore(webchat): added readme to display supported content-types

---

packages/components/package.json
packages/inject/package.json
packages/webchat/package.json
yarn.lock

chore(webchat): bump version

---

packages/client/package.json
packages/client/src/base.ts
packages/client/src/client.ts
packages/client/src/options.ts
yarn.lock

Adds handling in the messaging client to use the bp_messaging cookie for load balancing
Closes DEV-2400

chore(client): cookie handling for load balancer

---

packages/server/test/migration/global-diff.test.ts
packages/server/test/migration/utils/database.ts
packages/server/test/migration/utils/server.ts
test/jest.e2e.setup.ts

This PR adds the global diff migration test to sure that the code describing the tables is synced correctly with the migrations.

chore(tests): added global diff migration test

---

package.json
yarn.lock

Fixes random issues with binary.
Seems to be partially related to this issue: https://github.com/vercel/pkg/issues/1349

fix(pkg): revert to 5.2.0

---

packages/webchat/src/components/Composer.tsx
packages/webchat/src/store/composer.ts

Brought the changes from this PR: https://github.com/botpress/botpress/pull/11616 into the webchat.

chore(webchat): focus on composer when it gets unlocked

---

.github/workflows/tests.yml
.gitignore
cypress.json
package.json
packages/server/src/api.ts
packages/webchat/.parcelrc
packages/webchat/package.json
packages/webchat/src/core/socket.tsx
packages/webchat/src/declaration.d.ts
packages/webchat/src/globals.d.ts
packages/webchat/test/app.tsx
packages/webchat/test/e2e/basic.test.ts
packages/webchat/test/e2e/util.ts
packages/webchat/test/index.html
packages/webchat/test/tsconfig.json
test/cypress/plugins/index.ts
test/cypress/support/commands.ts
test/cypress/support/index.ts
yarn.lock

This PR adds the setup for running E2E tests on the webchat and adds a basic test that loads the webchat, configures it, and sends payloads.

chore(e2e): added basic e2e test for the webchat

---

packages/engine/src/distributed/redis/subservice.ts

Fixes a problem where trying to release a lock that was already timed out would cause an error to be logged to the console. In some edge cases it could mean that locked areas of the code could be running at two places at the same time. This PR implements lock refreshing to solve all these problems
Closes DEV-2490

fix(distributed): fix locks failing to release

---

package.json
packages/base/package.json
packages/board/package.json
packages/channels/package.json
packages/client/package.json
packages/components/package.json
packages/engine/package.json
packages/example/package.json
packages/framework/package.json
packages/inject/package.json
packages/server/package.json
packages/socket/package.json
packages/webchat/package.json
yarn.lock

chore(packages): update packages to v1.2.0

---

package.json
packages/server/package.json

Bumps to 1.2.1 to prepare release

chore(version): bump

---

packages/channels/src/base/channel.ts
packages/channels/src/base/service.ts
packages/server/src/instances/clearing/service.ts
packages/server/src/instances/lifetime/service.ts

Fixes an issue where conduits that are currently running wouldn't be cleared up when the server closes
Closes DEV-2566

fix(shutdown): fix channels not being cleared correctly

---

test/setup/database.ts

chore(tests): fix running pg tests more than once

---

.github/workflows/tests.yml
package.json
packages/webchat/test/e2e/util.ts
test/cypress/start.ts

This PR improves the Webchat E2E test setup by now having a single command to run the tests.

chore(tests): improve webchat tests setup

---

packages/studio/frontend/src/components/Layout/StatusBar/ActionItem.tsx
packages/studio/server/src/studio/actions/actions-router.ts
packages/studio/server/src/studio/cloud/cloud-router.ts
packages/studio/server/src/studio/cms/cms-router.ts
packages/studio/server/src/studio/code-editor/code-editor-router.ts
packages/studio/server/src/studio/config/config-router.ts
packages/studio/server/src/studio/flows/flows-router.ts
packages/studio/server/src/studio/hints/hints-router.ts
packages/studio/server/src/studio/manage/manage-router.ts
packages/studio/server/src/studio/media/media-router.ts
packages/studio/server/src/studio/nlu/nlu-router.ts
packages/studio/server/src/studio/qna/qna-router.ts
packages/studio/server/src/studio/server.ts
packages/studio/server/src/studio/studio-router.ts
packages/studio/server/src/studio/utils/custom-studio-router.ts

chore(studio): re-add cloud router

---

packages/studio/frontend/src/components/Layout/StatusBar/ActionItem.tsx
packages/studio/frontend/src/util/EventBus.ts
packages/studio/server/src/studio/actions/actions-router.ts
packages/studio/server/src/studio/cloud/cloud-router.ts
packages/studio/server/src/studio/cms/cms-router.ts
packages/studio/server/src/studio/code-editor/code-editor-router.ts
packages/studio/server/src/studio/config/config-router.ts
packages/studio/server/src/studio/flows/flows-router.ts
packages/studio/server/src/studio/hints/hints-router.ts
packages/studio/server/src/studio/manage/manage-router.ts
packages/studio/server/src/studio/media/media-router.ts
packages/studio/server/src/studio/nlu/nlu-router.ts
packages/studio/server/src/studio/qna/qna-router.ts
packages/studio/server/src/studio/server.ts
packages/studio/server/src/studio/studio-router.ts
packages/studio/server/src/studio/utils/custom-studio-router.ts

Fix socket connection by allowing all type of transports.

chore(studio): fix socket connection

---

.github/workflows/tests.yml
packages/studio/server/test/tsconfig.json
packages/studio/server/test/unit/lock.test.ts
test/jest.unit.config.ts

chore(ci_cd): run studio tests on ci

---

package.json
packages/server/package.json

chore(server): bump messaging to v1.2.3

---

packages/components/package.json
packages/components/src/renderer/choice.tsx
packages/components/src/renderer/dropdown.tsx
packages/webchat/package.json
yarn.lock

This PR fixes an issue with the dropdown component where the options would not disappear after a choice was made
**before**
https://user-images.githubusercontent.com/9640576/177391530-4e84a83e-9758-446d-b520-4edac389a25d.mp4
**after**
https://user-images.githubusercontent.com/9640576/177391016-3c4b651d-544c-4606-9d39-7b8ac027c8fd.mp4

fix(components): fix dropdown not disappearing after selection

---

package.json
packages/server/package.json

chore(server): bump messaging to v1.2.4

---

packages/board/package.json
packages/inject/package.json
packages/webchat/package.json
packages/webchat/src/components/messages/Message.tsx
packages/webchat/src/main.tsx
packages/webchat/src/typings.ts
packages/webchat/src/utils/webchatEvents.ts
yarn.lock

This brings back the ability to create a conversation from the iframe api

feat(webchat): create conversation from iframe api

---

packages/channels/README.md

chore(doc): add doc on legacy channels

---

packages/components/src/renderer/choice.tsx
packages/components/src/typings.ts

Same changes from https://github.com/botpress/botpress/pull/12111 applied to the messaging webchat

fix(components): focus composer when single choice btn is clicked

---

.github/workflows/upload-webchat-production.yml
.github/workflows/upload-webchat-staging.yml

- chore(gh-actions): update for breaking changes in s3@v2
- update prod

chore(gh-actions): update for breaking changes in s3@v2

---

packages/client/README.md

Otherwise request body is always `undefined`

fix(client): better instructions

---

.github/workflows/upload-webchat-staging.yml

So I can update the webchat styling in staging so Rohan can test it

feat(gh-actions): allow uploading webchat manually on staging

---

package.json
packages/base/src/users.ts
packages/server/package.json
packages/server/src/migrations/1.1.8-user-data.ts
packages/server/src/migrations/index.ts
packages/server/src/socket/manager.ts
packages/server/src/users/events.ts
packages/server/src/users/service.ts
packages/server/src/users/stream.ts
packages/server/src/users/table.ts
packages/server/test/unit/socket.test.ts
packages/socket/src/com.ts
packages/socket/src/socket.ts
packages/webchat/src/core/socket.tsx
packages/webchat/src/typings.ts

feat(webchat): add userData
